version: '3.3'
services:
                db:
                  image: mysql:latest
                  restart: always
                  environment:
                    MYSQL_DATABASE: 'vraw'
                    MYSQL_ROOT_PASSWORD: 'root2022'
                  ports:
                    - '3306:3306'
                  expose:
                    - '3306'
                  volumes:
                    - my-db:/var/lib/mysql